name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      VOLTA_FEATURE_PNPM: true

    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Lint JS
        run: pnpm lint:js
